server:
  port: 8777

spring:
  application:
    name: lecake-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.1.146:3306/dangao?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
    mapper-locations: classpath:mapper/*.xml


