server:

  port: 8083

eureka:

  client:

    serviceUrl:

      defaultZone: http://localhost:8761/eureka/

spring:

  application:

    name: order-feign

  thymeleaf:


redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      max-idle: 8
      min-idle: 0
