server:
  port: 8788
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: lacke-feign-gr

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
