server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: lecake-web
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
      encoding: UTF-8
      servlet:
          content-type: text/html