server:
  port: 8766

spring:
  application:
    name: lacke-provider-gr
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.1.146:3306/dangao?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root


    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000
      pool:
      max-active: 20
      max-wait: -1
      max-idle: 8
      min-idle: 0
#     MongoDB:
#       host: 127.0.0.1
#      mongodb:
#      database: 1809a
#      port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
